name: Master Snapshot Build

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  snapshot_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.6.0

      - name: Setup JAVA 19
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 19

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          SIGNING_KEY_STORE_PATH: ${{ github.workspace }}/${{ secrets.SIGNING_KEY_STORE_PATH }}
        run: |
          echo "$ENCODED_STRING" > keystore-b64.txt
          base64 -d keystore-b64.txt > "$SIGNING_KEY_STORE_PATH"

      - name: Set Google Service Credentials
        env:
          APP_DISTRIBUTION_JSON: ${{ secrets.APP_DISTRIBUTION_JSON}}
        run: |
          echo "$APP_DISTRIBUTION_JSON" > ${{ github.workspace }}/app-distribution.json

      - name: Set Google Services File
        env:
          SERVICES_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: |
          echo "$SERVICES_JSON" > ${{ github.workspace }}/app/google-services.json

      - name: Build Debug APK
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          GOOGLE_OAUTH_CREDS: ${{ secrets.GOOGLE_OAUTH_CREDS }}
          IGDB_CLIENT_ID: ${{secrets.IGDB_CLIENT_ID}}
          IGDB_CLIENT_SECRET: ${{secrets.IGDB_CLIENT_SECRET}}
        run: ./gradlew assembleDebug

      - name: Upload Debug APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Release To Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/app-distribution.json
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          GOOGLE_OAUTH_CREDS: ${{ secrets.GOOGLE_OAUTH_CREDS }}
          IGDB_CLIENT_ID: ${{secrets.IGDB_CLIENT_ID}}
          IGDB_CLIENT_SECRET: ${{secrets.IGDB_CLIENT_SECRET}}
        run: ./gradlew assembleDebug appDistributionUploadDebug
